[package]
name = "deepbook_wrapper"
version = "0.0.4"
edition = "2024.beta"

[dependencies]
# Mainnet version
deepbook = { local = "../deepbook", address = "0xcaf6ba059d539a97646d47f0b9ddf843e138d215e2a12ca1f4585d386f7aec3a" }
Pyth = { local = "../pyth", address = "0x04e20ddf36af412a4096f9014f4a565af9e812db9a05cc40254846cf6ed0ad91" }
multisig = { git = "https://github.com/MystenLabs/multisig-move.git", subdir = "move", rev = "main" }

[addresses]
deepbook_wrapper = "0x03aafc54af513d592bcb91136d61b94ea40b0f9b50477f24a3a9a38fca625174"
# deepbook_wrapper = "0x0"
