name: Build Protocol Fee Tickets Transaction

on:
  workflow_dispatch:

jobs:
  build-protocol-fee-tickets-tx:
    runs-on: ubuntu-latest
    env:
      # Multisig specific config
      MULTISIG_ADDRESS: ${{ vars.MULTISIG_ADDRESS }}
      MULTISIG_SIGNERS_BASE64_PUBKEYS: ${{ vars.MULTISIG_SIGNERS_BASE64_PUBKEYS }}
      MULTISIG_THRESHOLD: ${{ vars.MULTISIG_THRESHOLD }}
      MULTISIG_WEIGHTS: ${{ vars.MULTISIG_WEIGHTS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Build Protocol Fee Tickets
        run: npx tsx examples/ticket/create-multiple-tickets-withdraw-protocol-fees.ts
